apiVersion: lambda.aws.upbound.io/v1beta1
kind: Function
metadata:
  name: demo-lambda
spec:
  forProvider:
    region: us-east-1
    handler: lambda_function.lambda_handler
    role: arn:aws:iam::000000000000:role/lambda-exec-role
    runtime: python3.9
    filename: demo-lambda.zip
    sourceCodeHash: dGVzdGhhc2g=  # base64("testhash") to satisfy required field
  providerConfigRef:
    name: default
